# Generated by Django 3.0.2 on 2020-12-24 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='good_user',
            field=models.ManyToManyField(blank=True, related_name='good_user', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quote_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_recipe_name', to='eat.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quote_user',
            field=models.ManyToManyField(blank=True, related_name='quote_user', to=settings.AUTH_USER_MODEL, verbose_name='参考cookユーザー'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
